### ISSUE TITLE
Ouvrir la création d'évent à quiconque est admin d'organisation

### ISSUE THREAD

**Issue by vbastien** [AtelierSoude/OpenRepairPlatform#11]
Seulement les superuser peuvent rajouter des events pour l'instant

**Comment by jum-s** [comment]
https://trello.com/c/sBShWqiO/103-en-tant-quorganisateur-je-peux-cr%C3%A9er-des-%C3%A9venements-avec-un-limite-de-place-facultative
où "organisateur" = "admin de l'organisation"

**Comment by vbastien** [comment]
ça ne correspond pas vraiment à ce ticket, là l'emphase est sur la possibilité (non implémentée encore) de mettre un nombre de place facultatif, ici le problème est que le bouton "creer événement"/"creer lieu" n'est disponible que et seulement que pour le superutilisateur global, alors qu'il devrait l'être pour toute personne administrateur d'au moins une organisation
