### ISSUE TITLE
Toutes les organisations sont selectionnables lors de la création d'un objet

### ISSUE THREAD

**Issue by vbastien** [AtelierSoude/OpenRepairPlatform#12]
On peut mettre n'importe quelle orga quand on créé un event, un lieu etc..; (pas que la sienne)

**Comment by vbastien** [comment]
Partiellement résolu dans https://github.com/AtelierSoude/OpenRepairPlatform/commit/6459a341312fc4101d345186409aa03764705770 , reste à dynamiquement traiter les choix de lieux (pour les restreindres à ceux associés à l'événement)

**Comment by jum-s** [comment]
[chance] j'ai fait le coté event form, si ca te convient @vbastien jte laisse merger la PR ?

**Comment by vbastien** [comment]
Le owner=user dans le filter ça laissera qu'une seule personne par organization créer les événements non?

D'ailleurs je crois que la distinction masseventcreateform/eventcreateform n'a plus trop lieu, il faut qu'on en rediscute mais @ClemsP voulait fusionner les deux avec sa nouvelle interface je crois.

J'aime beaucoup le fields['organization'].queryset par contre à voir si je peux l'implémenter dans ce que j'ai fait, ça libérera un peu de charge processeur potentiellement si on peut tout préparer en 1 requete sql snas avoir à itérer sur les résultats

**Comment by jum-s** [comment]
oui seul le owner peut rajouter des events, comme le veut ce ticket trello https://trello.com/c/e7onGmx5/27-en-tant-quorganisateur-je-peux-cr%C3%A9er-des-comptes-utilisateurs-afin-de-les-rattacher-directement-%C3%A0-un-%C3%A9venement

la créa d'event en masse mérite une autre issue non?

j'ai découvert la méthode `.select_related('user')` qui permet de preparer une requete et eviter le query n+1

**Comment by vbastien** [comment]
(oui le rebase est ma bête noire)
cf https://github.com/AtelierSoude/OpenRepairPlatform/pull/16 pour la suite
