### ISSUE TITLE
Home page: Barre de navigation latérale s'affiche derrière les menu déroulants

### ISSUE THREAD

**Issue by Skrattoune** [AtelierSoude/OpenRepairPlatform#148]
Hello, j'ai trouvé des petits bugs d'affichage
quand on affiche la homepage en mode mobile ou browser etroit, 
il y a un problème d'ordre des z-index entre les menu déroulants du formulaire et la navbar latérale

cf http://test-openrepair.repaircafe-lausanne.ch/ (menu plus visible chez vous avec le nouvel affichage ou on choisit le code postal)

**Comment by ClemsP** [comment]
Alors oui en effet, cela a été réglé dans notre branche dev_branch. 

Il faut que je mette à jour correment la branche dev_fr_suisse avec les quelques modifications que j'ai fait entre temps.
