### ISSUE TITLE
Page Organizations: pb de placement des logos et des "titres" dans les cards

### ISSUE THREAD

**Issue by Skrattoune** [AtelierSoude/OpenRepairPlatform#149]
Il semble y avoir des problèmes avec les logos et les noms d'organisation qui semblent pas mal dépasser des cards (pb de resize?), aussi bien en mode telphone que browser normal (en tout cas sur mon Chrome)

https://reparons.org/user/organizations/
http://test-openrepair.repaircafe-lausanne.ch/user/organizations/

code: [openrepairplatform/user/templates/user/organization/organization_card.html](https://github.com/AtelierSoude/OpenRepairPlatform/blob/30ca273e8a58da0725e28448d3d905f175a31507/openrepairplatform/user/templates/user/organization/organization_card.html)

il semblerait que la card essaye de s'étirer / se répartir sur le maximum de colonnes si on regarde les deux sites
Chez nous, c'est comme s'il y avait une ligne vide dans la première colonne, le logo dans la 2e, et le titre sur la 3e colonne

essayez aussi de rétrécir la fenetre de browsing, ca fait des trucs marrants, et il ne semble pas avoir de resizing des logos

**Comment by ClemsP** [comment]
Oui j'ai constaté cela, et ça vient de la MAJ de Bootstrap vers la v5. 
Je m'en charge
