### ISSUE TITLE
Bug: ajout objet impossible par le public

### ISSUE THREAD

**Issue by DamSaulGoodMan** [AtelierSoude/OpenRepairPlatform#179]
Très régulièrement les personnes ne peuvent pas ajouter d'objets. Et pas uniquement quand ils ont pas de compte sur la plateforme.

**Comment by ClemsP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sur mobile, la modal d'ajout de stuff marche pas](https://trello.com/c/020UiMUY/280-sur-mobile-la-modal-dajout-de-stuff-marche-pas)
