### ISSUE TITLE
Bug: création d'event sans limite de place

### ISSUE THREAD

**Issue by DamSaulGoodMan** [AtelierSoude/OpenRepairPlatform#180]
Si on essaye de créer un événement sans limite de place, cela ne fonctionne pas. Pour contrer, il faut au préalable mettre un nombre de participants puis cocher la case "sans limite de participants".

**Comment by ClemsP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Evénement sans limite de place et sans réservation : affichage TOUJOURS réservation. problème d'affichage ou de validation du formulaire de création d'événement](https://trello.com/c/tfSTxckr/299-ev%C3%A9nement-sans-limite-de-place-et-sans-r%C3%A9servation-affichage-toujours-r%C3%A9servation-probl%C3%A8me-daffichage-ou-de-validation-du-formul)
