### ISSUE TITLE
Créer un package dédié aux mails?

### ISSUE THREAD

**Issue by vbastien** [AtelierSoude/OpenRepairPlatform#19]
Pour l'instant la seule fonction mail est send_booking_mail, mais en passant la réservation d'un formulaire à un api, je me demande si c'est pas une bonne idée de mettre tous les trucs liés aux mails dans leur propre package (sans urls.py vraiment interne) pour qu'elles soient plus indépendantes et plus tard rapidement accessible par celery?

**Comment by ClemsP** [comment]
Très pour et toi @jum-s  ?
