### ISSUE TITLE
Stockage des media (avatars, photos, etc) sur un stockage distinct du serveur de prod (CDN ou autre)

### ISSUE THREAD

**Issue by jum-s** [AtelierSoude/OpenRepairPlatform#7]
from [trello](https://trello.com/c/fnTkmBRk/2-stockage-des-media-avatars-photos-etc-sur-un-stockage-distinct-du-serveur-de-prod-cdn-ou-autre)

**Comment by jum-s** [comment]
message de david : 

"Dans un premier temps possible d'écrire sur le serveur, mais ce n'est pas une bonne idée pour les raisons indiquées ici :

http://whitenoise.evans.io/en/stable/django.html#serving-media-files

(on utilise Whitenoise pour servir les assets statiques)

Donc il faut utiliser un autre serveur, ou un CDN, ou quelquechose du genre, via django-storages. Voir:
https://django-storages.readthedocs.io/en/latest/index.html

Pour un exemple de configuration et une solution que l'on peut réutiliser, jeter un oeil à:
https://stackoverflow.com/questions/10390244/how-to-set-up-a-django-project-with-django-storages-and-amazon-s3-but-with-diff

en particulier, regarder les variables suivantes dans settings.py:
MEDIA_URL
STATIC_URL
MEDIA_ROOT
STATIC_ROOT
STATICFILES_STORAGE
DEFAULT_FILE_STORAGE
"

**Comment by almereyda** [comment]
You may ask your friends at IndieHosters to provide you an S3-compatible API through rook.io or minio.io
