### ISSUE TITLE
Réparer la boîte de dialogue réservation événement

### ISSUE THREAD

**Issue by vbastien** [AtelierSoude/OpenRepairPlatform#9]
La fenêtre de réservation met à jour la bdd avant même que l'utilisateur clique sur ok car mettre les modifications du modele dans form.is_valid(): ne fonctionne pas, il faut trouver comment contourner ça

**Comment by jum-s** [comment]
du lien du lien ! elle est ou la ligne dont tu parles?

**Comment by ClemsP** [comment]
L'issue est réglée non @vbastien ?

**Comment by vbastien** [comment]
Oui, manque plus que les boutons à mettre en jour en live. 
cf https://github.com/AtelierSoude/OpenRepairPlatform/commit/e7864655631b6220f605b053a0e2fbfa7ff4891e
et https://github.com/AtelierSoude/OpenRepairPlatform/commit/548109dc1411c557b5233289a581bc2975d1b32f
